generator:
  class: sfPropelGenerator
  param:
    model_class:           link
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              link
    plural:                links
    route_prefix:          link
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, =name, url]
      filter:  
        class: FALSE
      form:
        display: [name, url, description]
      edit:    ~
      new:     ~

