bot:
  class: sfPropelRouteCollection
  options:
    model:                bot
    module:               bot
    prefix_path:          /bot
    column:               id
    with_wildcard_routes: true

comment:
  class: sfPropelRouteCollection
  options:
    model:                comment
    module:               comment
    prefix_path:          /comment
    column:               id
    with_wildcard_routes: true

link:
  class: sfPropelRouteCollection
  options:
    model:                link
    module:               link
    prefix_path:          /link
    column:               id
    with_wildcard_routes: true

category:
  class: sfPropelRouteCollection
  options:
    model:                category
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

category_sort:
  url: /category/sort
  param: { module: category, action: sort }

link_sort:
  url: /link/sort
  param: { module: link, action: sort }

post:
  class: sfPropelRouteCollection
  options:
    model:                post
    module:               post
    prefix_path:          /post
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing


clearcache:
  url: /clearcache/
  param: { module: clearcache, action: index }

# default rules
homepage:
  url:   /
  param: { module: dashboard, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
