generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_propel_route:     1

    config:
      list:
        title: Group List

      edit:
        title: Edit Group

      filter:
        class: FALSE

      new:
        title: New Group
