<?php

/**
 * Skeleton subclass for representing a row from the 'bot' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jan 17 13:04:50 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Bot extends BaseBot
{
} // Bot
