<?php

/**
 * Skeleton subclass for performing query and update operations on the 'category' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jan 12 16:08:13 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CategoryPeer extends BaseCategoryPeer
{
    public static function getAllByRank(Criteria $criteria=null)
    {
        if (!$criteria) {
            $criteria = new Criteria();
        }

        $criteria->addAscendingOrderByColumn(CategoryPeer::RANK);

        return self::doSelect($criteria);
    }

    public static function retrieveByName($name)
    {
        $criteria = new Criteria();
        $criteria->addAnd(CategoryPeer::NAME, $name);

        return self::doSelectOne($criteria);
    }
} // CategoryPeer
