<?php


/**
 * Skeleton subclass for performing query and update operations on the 'comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jan 12 16:08:14 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CommentPeer extends BaseCommentPeer {
	public static function getLastComments($total=5) {
		$criteria = new Criteria();
		$criteria->addDescendingOrderByColumn(self::CREATED_AT);
		$criteria->setLimit($total);
		return self::doSelect($criteria);
	}
} // CommentPeer
