<?php

/**
 * Skeleton subclass for performing query and update operations on the 'link' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jan 12 16:08:14 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LinkPeer extends BaseLinkPeer
{
    public static function getAllByRank()
    {
        $criteria = new Criteria();
        $criteria->addAscendingOrderByColumn(LinkPeer::RANK);

        return self::doSelect($criteria);
    }
} // LinkPeer
