generator:
  class: sfPropelGenerator
  param:
    model_class:           bot
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              bot
    plural:                bots
    route_prefix:          bot
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, =ip, url, created_at]
      filter:
        class: FALSE
      form:    ~
      edit:    ~
      new:     ~

