# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View


default:
  http_metas:
    content-type: text/html

  metas:
    title:         Blog
    #description:  symfony project
    #keywords:     symfony, project
    language:     fr
    robots:       index, follow

  stylesheets:    [bootstrap.css, uniform.default.css, main.css]

  javascripts:    [jquery/jquery.1.7.1.js, bootstrap/bootstrap-modal.js, bootstrap/bootstrap-alerts.js, bootstrap/bootstrap-twipsy.js, bootstrap/bootstrap-popover.js, bootstrap/bootstrap-dropdown.js, bootstrap/bootstrap-scrollspy.js, bootstrap/bootstrap-modal.js, bootstrap/bootstrap-tabs.js, bootstrap/bootstrap-tabs.js, jquery/jquery.uniform.js, tiny_mce/jquery.tinymce.js, lightbox.js, main.js]

  has_layout:     true
  layout:         layout
